import * as React from "react";
import * as Types from "./types";

declare function StatusCard(props: {
  as?: React.ElementType;
  statusRow1Step1State?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow1Alert?: Types.Visibility.VisibilityConditions;
  statusRow1StatusStatusButton1?: Types.Visibility.VisibilityConditions;
  statusRow1StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow1StatusStatusMessage?: React.ReactNode;
  statusRow1StatusDate?: React.ReactNode;
  statusRow1StatusHour?: React.ReactNode;
  statusRow1AlertMessageText?: React.ReactNode;
  statusRow2Step2State?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow2Alert?: Types.Visibility.VisibilityConditions;
  statusRow2StatusStatusButton1?: Types.Visibility.VisibilityConditions;
  statusRow2StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow2StatusStatusMessage?: React.ReactNode;
  statusRow2StatusDate?: React.ReactNode;
  statusRow2StatusHour?: React.ReactNode;
  statusRow2AlertMessageText?: React.ReactNode;
  statusRow3StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow3StatusStatusButton1?: Types.Visibility.VisibilityConditions;
  statusRow3Step3State?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow3Alert?: Types.Visibility.VisibilityConditions;
  statusRow3StatusStatusMessage?: React.ReactNode;
  statusRow3StatusDate?: React.ReactNode;
  statusRow3StatusHour?: React.ReactNode;
  statusRow3AlertMessageText?: React.ReactNode;
  statusRow4Step4State?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow4StatusStatusButton1?: Types.Visibility.VisibilityConditions;
  statusRow4StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow4Alert?: Types.Visibility.VisibilityConditions;
  statusRow4StatusStatusMessage?: React.ReactNode;
  statusRow4StatusDate?: React.ReactNode;
  statusRow4StatusHour?: React.ReactNode;
  statusRow4AlertMessageText?: React.ReactNode;
  statusRow5Step5State?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow5StatusStatusButton1?: Types.Visibility.VisibilityConditions;
  statusRow5StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow5Alert?: Types.Visibility.VisibilityConditions;
  statusRow5StatusStatusMessage?: React.ReactNode;
  statusRow5StatusDate?: React.ReactNode;
  statusRow5StatusHour?: React.ReactNode;
  statusRow5AlertMessageText?: React.ReactNode;
  statusRow6Step6State?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow6StatusStatusButton1?: Types.Visibility.VisibilityConditions;
  statusRow6StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow6Alert?: Types.Visibility.VisibilityConditions;
  statusRow6StatusStatusMessage?: React.ReactNode;
  statusRow6StatusDate?: React.ReactNode;
  statusRow6StatusHour?: React.ReactNode;
  statusRow6AlertMessageText?: React.ReactNode;
  statusRow7Step7State?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow7StatusStatusButton1?: Types.Visibility.VisibilityConditions;
  statusRow7StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow7Alert?: Types.Visibility.VisibilityConditions;
  statusRow7StatusStatusMessage?: React.ReactNode;
  statusRow7StatusDate?: React.ReactNode;
  statusRow7StatusHour?: React.ReactNode;
  statusRow7AlertMessageText?: React.ReactNode;
}): React.JSX.Element;
