import * as React from "react";
import * as Types from "./types";

declare function TableBodyRow(props: {
  as?: React.ElementType;
  variant?: "Base" | "status process" | "status finished" | "status negative";
  date?: React.ReactNode;
  hour?: React.ReactNode;
  aproxCompletationDate?: React.ReactNode;
  servicesFormattedId?: React.ReactNode;
  deviceBrandAndModel?: React.ReactNode;
  serialNumber?: React.ReactNode;
  deviceType?: React.ReactNode;
  departmentOrContact?: React.ReactNode;
  powerAdapter?: React.ReactNode;
  dataBackup?: React.ReactNode;
  requestOrIssue?: React.ReactNode;
  accesories?: React.ReactNode;
  observations?: React.ReactNode;
  statusRow1StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow1Variant?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow1Alert?: Types.Visibility.VisibilityConditions;
  statusRow1StatusDate?: React.ReactNode;
  statusRow1StatusHour?: React.ReactNode;
  statusRow1AlertMessageText?: React.ReactNode;
  statusRow1StatusStatusActionButton?: Types.Visibility.VisibilityConditions;
  statusRow1StatusStatusMessage?: React.ReactNode;
  statusRow2Variant?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow2StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow2Alert?: Types.Visibility.VisibilityConditions;
  statusRow2StatusDate?: React.ReactNode;
  statusRow2StatusHour?: React.ReactNode;
  statusRow2AlertMessageText?: React.ReactNode;
  statusRow2StatusStatusActionButton?: Types.Visibility.VisibilityConditions;
  statusRow2StatusTitle?: React.ReactNode;
  statusRow2StatusStatusMessage?: React.ReactNode;
  statusRow3Variant?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow3StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow3Alert?: Types.Visibility.VisibilityConditions;
  statusRow3StatusDate?: React.ReactNode;
  statusRow3StatusHour?: React.ReactNode;
  statusRow3AlertMessageText?: React.ReactNode;
  statusRow3StatusStatusActionButton?: Types.Visibility.VisibilityConditions;
  statusRow3StatusStatusMessage?: React.ReactNode;
  statusRow4Variant?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow4StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow4Alert?: Types.Visibility.VisibilityConditions;
  statusRow4StatusDate?: React.ReactNode;
  statusRow4StatusHour?: React.ReactNode;
  statusRow4AlertMessageText?: React.ReactNode;
  statusRow4StatusStatusActionButton?: Types.Visibility.VisibilityConditions;
  statusRow4StatusStatusMessage?: React.ReactNode;
  statusRow5Variant?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow5StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow5Alert?: Types.Visibility.VisibilityConditions;
  statusRow5StatusDate?: React.ReactNode;
  statusRow5StatusHour?: React.ReactNode;
  statusRow5AlertMessageText?: React.ReactNode;
  statusRow5StatusStatusActionButton?: Types.Visibility.VisibilityConditions;
  statusRow5StatusStatusMessage?: React.ReactNode;
  statusRow6Variant?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow6StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow6Alert?: Types.Visibility.VisibilityConditions;
  statusRow6StatusDate?: React.ReactNode;
  statusRow6StatusHour?: React.ReactNode;
  statusRow6AlertMessageText?: React.ReactNode;
  statusRow6StatusStatusActionButton?: Types.Visibility.VisibilityConditions;
  statusRow6StatusStatusMessage?: React.ReactNode;
  statusRow7Variant?: "Base" | "active" | "check" | "no_state" | "hidden";
  statusRow7StatusActionPopup?: Types.Visibility.VisibilityConditions;
  statusRow7Alert?: Types.Visibility.VisibilityConditions;
  statusRow7StatusDate?: React.ReactNode;
  statusRow7StatusHour?: React.ReactNode;
  statusRow7AlertMessageText?: React.ReactNode;
  statusRow7StatusStatusActionButton?: Types.Visibility.VisibilityConditions;
  statusRow7StatusStatusMessage?: React.ReactNode;
}): React.JSX.Element;
